title: Restaurante Delicias
description: Sistema de gestión de ventas y menús
baseurl: "" # si está en un subdirectorio, ej: "/restaurante"
url: "https://reneleonidas.github.io" # tu URL de GitHub Pages